services:
  apache:
    container_name: ${projectName}_apache
    build: ./docker/apache
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    ports:
      - ${portWebserver}:80
    environment:
      - WEB_DOCUMENT_ROOT=/app

  db:
    container_name: ${projectName}_db
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/tmp:/tmp
      - ./docker/database:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - ${portDatabase}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${dbName}
      MYSQL_USER: ${dbUser}
      MYSQL_PASSWORD: ${dbPassword}

volumes:
  db_data:
