name: 'Main Merge'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full clone necessary for proper merge

      - name: Nightly Merge Main in Develop
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'main'
          development_branch: 'develop'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Nightly Merge RC in Develop
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'rc'
          development_branch: 'develop'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Nightly Merge Main in RC
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'main'
          development_branch: 'rc'
          allow_ff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}